services:
  php:
    build:
      context: docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
      PHP_CS_FIXER_IGNORE_ENV: 1 # TODO: Remove when PHPCS supports PHP8.4
    volumes:
      - .:/var/www/html:cached
      - php_history:/root/history
    ports:
      - '8080:80'
volumes:
  php_history: ~
