version: '3'

vars:
  PHP: '{{if not .LOCALLY}}docker compose exec -it php{{end}}'

env:
  APP_ENV: dev

dotenv:
  - '.env.{{APP_ENV}}.local'
  - '.env.{{APP_ENV}}'
  - '.env.local'
  - '.env'

tasks:
  install:
    cmd: '{{.PHP}} composer install {{.CLI_ARGS}}'
    sources:
      - composer.json
      - composer.lock
    generates:
      - vendor/autoload.php
  up:
    cmds:
      - 'docker compose up --detach --remove-orphans {{.CLI_ARGS}}'
      - task: install
  down: 'docker compose down --remove-orphans {{.CLI_ARGS}}'
  start:
    cmds:
      - 'docker compose start {{.CLI_ARGS}}'
      - task: install
  stop: 'docker compose stop {{.CLI_ARGS}}'
  php: '{{.PHP}} bash'

  var:
    cmd: mkdir -p var
    status:
      - test -d var
    silent: true
    internal: true

  test-unit:
    deps: [var, install]
    cmd: '{{.PHP}} vendor/bin/phpunit --group=unit {{.CLI_ARGS}}'

  test-integration:
    deps: [var, install]
    cmds:
      - '{{.PHP}} bin/console doctrine:database:create --if-not-exists --env=test'
      - '{{.PHP}} bin/console doctrine:migrations:migrate --no-interaction --env=test'
      - '{{.PHP}} vendor/bin/phpunit --group=integration {{.CLI_ARGS}}'
      - '{{.PHP}} bin/console doctrine:database:drop --force --env=test'
  env:
    APP_ENV: test

  doctrine-create:
    deps: [ var, install ]
    cmd: '{{.PHP}} bin/console doctrine:database:create --if-not-exists {{.CLI_ARGS}}'

  migrations-migrate:
    deps: [ var, install ]
    cmd: '{{.PHP}} bin/console doctrine:migrations:migrate --no-interaction {{.CLI_ARGS}}'

  migrations-diff:
    deps: [var, install]
    cmd: '{{.PHP}} bin/console doctrine:migrations:diff'

  doctrine-validate:
    deps: [var, install]
    cmd: '{{.PHP}} bin/console doctrine:schema:validate'

  schema-validate:
    deps: [ var, install ]
    cmd: '{{.PHP}} bin/console schema:validate'

  clear:
    deps: [ var, install ]
    cmd: '{{.PHP}} bin/console cache:clear'

  fixcs:
    deps: [var, install]
    cmd: '{{.PHP}} vendor/bin/php-cs-fixer fix --diff --verbose {{.CLI_ARGS}}'
  lint:
    cmds:
      - task: fixcs
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  rector-fix:
    deps: [var, install]
    cmd: '{{.PHP}} vendor/bin/rector process {{.CLI_ARGS}}'
  rector:
    deps: [var, install]
    cmds:
      - task: rector-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  phpstan:
    deps: [var, install]
    cmd: '{{.PHP}} vendor/bin/phpstan analyse -c phpstan.neon {{.CLI_ARGS}}'

  composer-normalize-fix:
    deps: [install]
    cmds:
      - '{{.PHP}} composer bump {{.CLI_ARGS}}'
      - '{{.PHP}} composer normalize --diff {{.CLI_ARGS}}'
  composer-normalize:
    cmds:
      - task: composer-normalize-fix
        vars:
          CLI_ARGS: '--dry-run {{.CLI_ARGS}}'

  composer-validate: '{{.PHP}} composer validate --strict --no-check-publish {{.CLI_ARGS}}'

  composer-audit: '{{.PHP}} composer audit {{.CLI_ARGS}}'

  composer-require-check:
    deps: [var, install]
    cmd: '{{.PHP}} vendor/bin/composer-require-checker check {{.CLI_ARGS}}'

  composer-unused-check:
    deps: [ var, install ]
    cmd: '{{.PHP}} vendor/bin/composer-unused {{.CLI_ARGS}}'

  deptrac-directories:
    deps: [ var, install ]
    cmd: '{{.PHP}} vendor/bin/deptrac analyze --config-file=deptrac.directories.yaml --cache-file=var/.deptrac.directories.cache {{.CLI_ARGS}}'

  check:
    cmds:
      - task: lint
      - task: phpstan
      - task: rector
      - task: deptrac-directories
      - task: test-unit
      - task: test-integration
      - task: composer-validate
      - task: composer-audit
      - task: composer-normalize
      - task: composer-require-check
      - task: composer-unused-check