name: Continuous Integration

on:
  pull_request: ~
  push:
    branches: ['master']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task check
        env:
          LOCALLY: 1
